import { BondageScenario } from './bondage-scenarios';

export const scenarios: BondageScenario[] = [
  {
    id: 'rope',
    bondage: `*You wake up in the dimly lit room, heart already racing as I stand over you with a calm, confident smile.* **"Tonight, you're mine to restrain,"** *I say softly, my voice low and reassuring. I start with your wrists. I take a length of soft, black rope, and loop it around both wrists several times before cinching it tight with a secure knot, pulling your hands together behind your back. The rope bites just enough to remind you of your helplessness without causing pain, locking your arms in place. Next, I move to your elbows. I draw them closer together, wrapping the next rope around them in careful, overlapping coils. With each pass, I pull firmly, forcing your elbows to nearly touch, arching your chest forward slightly. The binding is snug and unyielding, emphasizing the curve of your body as your shoulders are drawn back. I shift downward to your ankles. Crossing them slightly, I wind the rope around them multiple times, knotting it securely so your feet are bound tight. Then come your knees. I wrap the rope just above and below the joints, pulling them together with steady pressure until they're pressed close, the bindings restrict your legs from parting. For your calves, I add more rope, encircling the thick muscles in even loops that compress them gently but inescapably against each other. Finally, your thighs. I bind them high up, just below the curve of your ass with thick coils of rope that dig in firmly, forcing your legs into a tight column from hips to ankles. The full leg bondage leaves you completely immobile below the waist.*`,
    gag: `*Once your body is bound, I pick up a soft cloth gag. I hold it to your lips and command,* **"Open."** *As you obey, I push the cloth deep into your mouth, filling it completely before tying a strip of fabric around your head in a cleave gag to hold it in place. The gag muffles any sounds you might make, turning your protests or moans into soft, helpless murmurs.*`,
    blindfold: `*Last, the blindfold. I drape a thick, black cloth over your eyes, tying it securely at the back of your head. Darkness envelops you instantly, heightening every touch, every sound, and every tug of the ropes against your skin.*`,
  },
  {
    id: 'leather',
    bondage: `*You wake up in the dimly lit room, heart already racing as I stand over you with a calm, confident smile.* **"Tonight, you're mine to restrain,"** *I say softly, my voice low and commanding. I begin with your wrists. I take a wide, thick black leather belt and wrap it around both wrists, the smooth leather soft against your skin. I thread the end through the heavy metal buckle and pull it tight with a satisfying 'creak', tugging it firmly until the leather bites just enough to hold you helpless without discomfort. Your hands are now locked securely behind your back. Next, I move to your elbows. I draw them closer together and slide another sturdy leather belt around them. With each pull, I yank the belt tighter, forcing your elbows to nearly touch and arching your chest forward. The thick leather holds unyieldingly, the buckles clicking into place as your shoulders are drawn back. I shift downward to your ankles. Crossing them slightly, I encircle them with a wide leather belt, wrapping it tight before buckling it snugly, the leather compressing your ankles together inescapably. Then come your knees. I wrap one belt just above the joints and another just below, pulling each buckle hard until your knees are pressed tightly together, the straps restricting any attempt to part your legs. For your calves, I add thick leather belts that hug the muscles firmly, buckling them in place so your lower legs are fused together. Finally, your thighs. I take the widest belts and bind them high up, just below the curve of your ass. I pull each buckle ruthlessly tight, the leather digging in with a deep, possessive grip that forces your legs into a single, immobile column from hips to ankles. The full leather bondage leaves you completely helpless, the belts creaking softly with every tiny struggle. As a final touch, I also padlocked all the leather belts~!*`,
    gag: `*Once your body is securely bound in leather, I pick up a thick leather panel gag. I press the soft padded leather against your lips and command,* **"Open wide."** *As you obey, I push the ball of the panel deep into your mouth, filling and sealing it completely. I buckle the heavy straps tightly behind your head — one over the top and one around your neck — pulling them until the gag is locked in place. The thick leather muffles every sound you make, turning your protests or moans into soft, helpless whimpers trapped behind the unyielding panel.*`,
    blindfold: `*Finally, the blindfold. I take a wide, padded black leather blindfold and place it firmly over your eyes, the soft inner lining pressing against your skin. I buckle the straps securely at the back of your head, pulling them tight so the leather molds perfectly to your face. Complete darkness envelops you instantly, every creak of the belts and every touch now magnified in the absence of sight.*`,
  },
  {
    id: 'tape',
    bondage: `*You wake up in the dimly lit room, heart already racing as I stand over you with a calm, confident smile.* **"Tonight, you're getting taped up tight,"** *I say softly, my voice low and commanding. I start with your wrists. I take a fresh roll of thick black electrical tape and begin wrapping it around both wrists in overlapping layers. The tape stretches slightly as I pull it tight with each pass, the shiny tape sticking to itself and your skin. I keep winding until your wrists are completely encased. With a final hard pull, I tear the tape and smooth it down, locking your hands securely behind your back. Next, I move to your elbows. I draw them close together and start wrapping the tape around them in tight, overlapping spirals. Each layer is pulled with steady force, the tape creaking faintly as it compresses and fuses into a solid black band, forcing your elbows nearly together and arching your chest forward. I shift downward to your ankles. Crossing them slightly, I wind the electrical tape around them in multiple tight layers, stretching and smoothing each pass until your ankles are fused together. Then come your knees. I wrap thick bands of tape just above and below the joints, pulling each layer tight so your knees are pressed firmly together, the tape restricting any attempt to separate your legs. For your calves, I add more layers of the sticky black tape, encircling the muscles until they are compressed and sealed tightly against each other. Finally, your thighs. I take the roll and bind them high up, just below the curve of your ass. I pull each layer with maximum tension, the tape stretching and snapping back as it forms a thick, rigid column from your hips all the way down to your ankles.*`,
    gag: `*Once your body is fully encased in tape, I pick up a thick wad of cloth and a fresh roll of black electrical tape. I push the cloth deep into your mouth, filling it completely, then seal your lips shut with several tight horizontal layers of the electrical tape. I continue wrapping the tape around your head, covering from just under your nose to under your chin in smooth, overlapping passes, pulling it tight until your gag muffles every sound into faint, desperate murmurs.*`,
    blindfold: `*Last, the blindfold. I place a thick cotton pad over your eyes and begin wrapping the black electrical tape around your head in tight, overlapping layers. I keep winding until the tape forms a wide, glossy black band that completely blocks out all light, sealing the blindfold in place with firm pressure. Darkness swallows you instantly, every tiny creak and pull of the tape now feeling ten times more intense.*`,
  },
  {
    id: 'scarves',
    bondage: `*You wake up in the dimly lit room, heart already racing as I stand over you with a calm, confident smile.* **"Tonight, I'm tying you up with soft scarves,"** *I say softly, my voice low and reassuring. I start with your wrists. I take a long black scarf and loop it around both wrists several times, the smooth silk fabric gliding over your skin. I pull it snug and tie a secure knot, then add another scarf over the first for extra layers, cinching it firmly so your hands are held securely behind your back. The scarves feels deceptively gentle but holds you inescapably. Next, I move to your elbows. I draw them closer together and wrap a long black scarf around them in careful, overlapping coils. With each pass, I pull steadily, forcing your elbows to nearly touch and arching your chest forward slightly. I tie it off tightly, the layered cloth creates a firm, padded restraint that emphasizes the curve of your body as your shoulders are drawn back. I shift downward to your ankles. Crossing them slightly, I wind another long scarf around them multiple times before tying a strong knot, compressing your ankles together. Then come your knees. I wrap a scarf just above and below the joints, pulling them together with steady pressure until they're pressed close, restricting your legs from parting. For your calves, I add more scarves, encircling the thick muscles in even loops and tying them securely so your lower legs are held firmly against each other. Finally, your thighs. I take two long scarves and bind them high up, just below the curve of your ass, overlapping them before knotting tightly. The layered scarves force your legs into a tight column from hips to ankles.*`,
    gag: `*Once your body is bound, I pick up a soft silk scarf. I hold the bunched fabric to your lips and command,* **"Open."** *As you obey, I push the silky material deep into your mouth, filling it completely. I then take another long scarf and tie it tightly around your head in a cleave gag, pulling it firmly between your teeth to hold the stuffing in place. The soft fabric muffles any sounds you might make, turning your protests or moans into gentle, helpless murmurs.*`,
    blindfold: `*Last, the blindfold. I fold a thick, dark scarf and drape it over your eyes, tying it securely at the back of your head with a firm knot. The soft silk blocks out all light instantly, enveloping you in darkness and heightening every touch and every tug of the scarves against your skin.*`,
  },
  {
    id: 'chains',
    bondage: `*You wake up in the dimly lit room, heart already racing as I stand over you with a calm, confident smile.* **"Tonight, you're getting locked in cold steel chains,"** *I say softly, my voice low and commanding. I start with your wrists. I take a length of cold, heavy steel chain and wrap it around both wrists several times. The metal links clink and bite into your skin as I pull it tight. I thread a thick padlock through the links and snap it shut with a loud click, locking your hands securely behind your back. The weight of the chains pulls your arms down slightly, reminding you of your helplessness with every small movement. Next, I move to your elbows. I draw them closer together and wrap another heavy chain around them in overlapping loops. With each pull, the cold steel digs in firmly, forcing your elbows to nearly touch and arching your chest forward. I add a second padlock, snapping it shut with a decisive click, the chains now holding your shoulders back tightly. I shift downward to your ankles. Crossing them slightly, I wind a thick steel chain around them multiple times, the links clanking loudly as I pull it taut and secure it with a heavy padlock. Then come your knees. I wrap chains just above and below the joints, pulling them together with steady pressure until your knees are pressed close, the metal restricting any attempt to part your legs. I lock each section with its own padlock. For your calves, I add more chains, encircling the thick muscles in even loops and locking them securely so your lower legs are fused together by cold steel. Finally, your thighs. I take the heaviest chains and bind them high up, just below the curve of your ass, wrapping the steel in multiple tight coils. I pull each section hard, the metal digging in with unyielding pressure, then lock them with multiple padlocks.*`,
    gag: `*Once your body is locked in chains, I pick up a large ball gag. I press the cold plastic ball against your lips and command,* **"Open."** *As you obey, I push the ball deep into your mouth, stretching your jaw wide. I buckle the thick leather straps attached to the gag tightly around your head, pulling them until the gag is locked firmly in place. The ball muffles your sounds into deep, helpless groans.*`,
    blindfold: `*Last, the blindfold. I take a heavy padded leather blindfold reinforced with small steel rings and place it firmly over your eyes. I thread a thin chain through the rings and lock it securely at the back of your head with a small padlock. Complete darkness envelops you instantly, heightening every clink of the chains and every cold touch of the metal against your body.*`,
  },
];
